image: node:latest

before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y && apt-get intall ruby-dev -y)'
    - eval $(ssh-agent -s)
    - gem install dpl --user-install

stages:
    - staging
    - production

staging:
    type: deploy
    stage: staging
    image: ruby:latest
    script:
        - export PATH=$PATH:/home/gitlab-runner/.gem/ruby/2.5.0/bin
        - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
    only:
        - staging
    tags:
        - ugrad

production:
    type: deploy
    stage: production
    image: ruby:latest
    script:
        - export PATH=$PATH:/home/gitlab-runner/.gem/ruby/2.5.0/bin
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    only:
        - main
    tags:
        - ugrad