export default {
  // baseURL: "http://localhost:8000/api/",
  baseURL: "https://grp11-dal-media-backend-prod.herokuapp.com/api/",
  getPosts: "posts",
  createPost: "posts/create",
  editPost: "posts/update",
  deletePost: "posts/delete",
  likeDislikePost: "posts/like-dislike-post",
  commentOnPost: "posts/comment-post",
  getComments: "posts/comments",
  searchPost: "posts/search",
  getEvents: "events",
  createEvent: "events/create",
  deleteEvent: "events/delete",
  editEvent: "events/update",
  users: "/users",
  signIn: "/users/signin",
  signUp: "users/signup",
  getLoggedInUser: "/users/current",
  createBlog: "blogs/create",
  getBlogs: "blogs/",
  updateBlog: "blogs",
  changePassword: "users/change-password",
  forgotPassword: "otp/send",
  resetPassword: "users/reset-password",
  profile: "users/getUserProfile",
  editProfile: "users/editprofile",
  groups: "groups",
  groupMembers: "members",
  usersToAdd: "usersToAdd",
  files: "files",
  createPoll: "polls/create",
  getPolls: "polls",
  getRequests: "friends/request",
  getFriends: "friends",
};
